name: 检查上游更新

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: 检出本仓库
        uses: actions/checkout@v4

      - name: 获取上游最新 commit
        run: |
          set -e

          LATEST_COMMIT=$(git ls-remote https://github.com/gedoor/legado.git refs/heads/master | cut -f1)
          echo "最新上游提交: $LATEST_COMMIT"

          if [ -f .last_upstream_commit ]; then
            LAST_COMMIT=$(cat .last_upstream_commit)
          else
            LAST_COMMIT="none"
          fi

          echo "之前记录提交: $LAST_COMMIT"

          if [ "$LATEST_COMMIT" != "$LAST_COMMIT" ]; then
            echo "$LATEST_COMMIT" > .last_upstream_commit

            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add .last_upstream_commit
            git commit -m "trigger: upstream updated to $LATEST_COMMIT"

            git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git push
          else
            echo "无更新，跳过构建。"
          fi
