name: 清理旧的工作流记录

on:
  workflow_dispatch:

jobs:
  delete_workflow_runs:
    runs-on: ubuntu-latest

    steps:
    - name: 删除旧的 workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 2         # 保留最近 2 天内的记录
        keep_minimum_runs: 3   # 至少保留最近 3 次运行
