name: 清理Actions
on:
  workflow_dispatch:
   schedule:
     - cron: 0 3 */1 * *

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0  # 保留每个工作流的最近 5 次运行记录
